#!/bin/bash

# ============================================================================
# PostgreSQL Upgrade Pre-Flight Checklist
# Project: Numerix (kmndhvzjyhyiwwdmgyqg)
# ============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 PostgreSQL Upgrade Pre-Flight Checklist"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "📋 PRE-UPGRADE CHECKLIST"
echo ""
echo "Before running the upgrade, complete these steps:"
echo ""
echo "1. ✅ Run SQL Pre-Upgrade Checks"
echo "   → Open Supabase Dashboard → SQL Editor"
echo "   → Run queries from: sql/postgres-upgrade-checks.sql"
echo "   → Save all results (version, extensions, row counts)"
echo ""
echo "2. ✅ Create Database Backup"
echo "   → Run: ./backup-database.sh"
echo "   → OR use Supabase Dashboard → Database → Backups"
echo ""
echo "3. ✅ Verify Backup"
echo "   → Test restore to staging (if available)"
echo "   → Verify backup file exists and is valid"
echo ""
echo "4. ✅ Schedule Maintenance Window"
echo "   → Expected downtime: 5-15 minutes"
echo "   → Notify users/stakeholders"
echo ""
echo "5. ✅ Check Application Status"
echo "   → Ensure no critical operations running"
echo "   → Document current version"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 SQL CHECKS TO RUN (in Supabase SQL Editor)"
echo ""
echo "Run these queries from sql/postgres-upgrade-checks.sql:"
echo ""
echo "  [ ] 1. Current Postgres Version"
echo "  [ ] 2. Installed Extensions"
echo "  [ ] 3. Extension Objects Check"
echo "  [ ] 4. Critical Extensions Version"
echo "  [ ] 5. Active Connections"
echo "  [ ] 6. Long-Running Queries"
echo "  [ ] 7. Table Row Counts"
echo "  [ ] 8. Index Bloat/Vacuum"
echo "  [ ] 9. Replication Status"
echo "  [ ] 10. Security-Definer Functions"
echo "  [ ] 11. Deprecated Features"
echo "  [ ] 12. Numerix-Specific Tables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 UPGRADE STEPS"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/kmndhvzjyhyiwwdmgyqg/settings/database"
echo ""
echo "2. Click 'Upgrade' or 'Change Version'"
echo ""
echo "3. Select latest patched version"
echo ""
echo "4. Follow the upgrade wizard"
echo ""
echo "5. Wait for completion (5-15 minutes)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ POST-UPGRADE VERIFICATION"
echo ""
echo "Run these checks immediately after upgrade:"
echo ""
echo "  [ ] 1. Verify new version (SELECT version();)"
echo "  [ ] 2. Check extensions still present"
echo "  [ ] 3. Verify row counts match pre-upgrade"
echo "  [ ] 4. Test application queries"
echo "  [ ] 5. Check for errors in logs"
echo "  [ ] 6. Run application smoke tests"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 FILES AVAILABLE"
echo ""
echo "  • sql/postgres-upgrade-checks.sql - All SQL checks"
echo "  • backup-database.sh - Backup script"
echo "  • UPGRADE_POSTGRES.md - Detailed guide"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
